name: CD - Deploy to Render

on:
  workflow_run:
    workflows: ["CI - Build and Test"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy Hook
        id: deploy
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}

  rollback:
    needs: deploy
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Auto Rollback
        run: |
          DEPLOY_ID=$(curl -s -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            "https://api.render.com/v1/services/srv-d7v5785ckfvc738sqtgg/deploys?limit=10" \
            | tr ',' '\n' | grep -A1 '"live"' | grep '"id"' | head -1 | cut -d'"' -f4)
          
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            "https://api.render.com/v1/services/srv-d7v5785ckfvc738sqtgg/deploys/$DEPLOY_ID/rollback"